#!/bin/bash
MASTER=spark://captain:7077
JAR_FILE=/home/hadoop/code/spark/MySpark/build/libs/MySpark.jar

# Submit
spark-submit --class com.rueggerllc.spark.apps.StreamingWordCount --master $MASTER $JAR_FILE $*
