#!/bin/bash

MASTER=local[2]
JAR_FILE=/home/hadoop/code/spark/MySpark/build/libs/MySpark.jar
HOST=captain
PORT=9999

# In terminal:
# nc -lk 9999
# -l 	listen
# -k 	keep open

# Submit
spark-submit --class com.rueggerllc.spark.apps.StreamingWordCount --master $MASTER $JAR_FILE $HOST $PORT
